// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbnKUtsXtoKoJ2g4jccoodpWoJMINUC7o',
    appId: '1:593751218507:web:8ad02c74d5f74c028370ce',
    messagingSenderId: '593751218507',
    projectId: 'signup-project-260cd',
    authDomain: 'signup-project-260cd.firebaseapp.com',
    storageBucket: 'signup-project-260cd.appspot.com',
    measurementId: 'G-1W02PNTESS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVBnrpcUiXkP1Tib3Ny2qoGyv9SQJW0No',
    appId: '1:593751218507:android:3e0916fa0aae220e8370ce',
    messagingSenderId: '593751218507',
    projectId: 'signup-project-260cd',
    storageBucket: 'signup-project-260cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUlweXsOSCYEU8EzPpX9S2O8jChOyvxzg',
    appId: '1:593751218507:ios:8b9faf485bc962d28370ce',
    messagingSenderId: '593751218507',
    projectId: 'signup-project-260cd',
    storageBucket: 'signup-project-260cd.appspot.com',
    iosClientId: '593751218507-c4q45ub6a6v5vjideedul7qcg8l05uhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUlweXsOSCYEU8EzPpX9S2O8jChOyvxzg',
    appId: '1:593751218507:ios:1041c4d13cd450d38370ce',
    messagingSenderId: '593751218507',
    projectId: 'signup-project-260cd',
    storageBucket: 'signup-project-260cd.appspot.com',
    iosClientId: '593751218507-pas38ghkp8r7aikk37q9gosk7tdlj2m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxLogin.RunnerTests',
  );
}
